version: "3.8"
services:
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
            - PMA_ARBITRARY=1
    api:
        build:
            context: .
        environment:
            - DATABASE_URL=mysql://root:root@mysql:3306/db_keuangan
        ports:
            - "3001:3001"
        container_name: api
    nginx:
        restart: always
        image: nginx:latest
        container_name: nginx
        volumes:
            - "./server:/etc/nginx/conf.d/default"
        ports:
            - "8090:80"
        depends_on:
            - api
