version: "3.8"
services:
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
            - PMA_ARBITRARY=1
        volumes:
            - phpmyadmin_data:/usr/share/nginx/html/phpmyadmin
    api:
        build:
            context: .
        environment:
            - DATABASE_URL=mysql://root:root@mysql:3306/db_keuangan
        ports:
            - "3001:3001"
        container_name: api
    mysql:
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql_data:/var/lib/mysql
    nginx:
        restart: always
        image: nginx:latest
        container_name: nginx
        volumes:
            - "./server:/etc/nginx/conf.d/default"
        ports:
            - "8090:80"
        depends_on:
            - api
volumes:
    phpmyadmin_data:
    mysql_data:
